name: Obfuscate blocklist to avoid use of direct raw url of block.txt

on:
  push:
    branches:
      - main
    paths:
      - block.txt

jobs:
  obfuscate-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes with rebase
        id: pull_rebase_latest
        run: |
          set -e
          git pull --rebase "https://x-access-token:${{ secrets.CUSTOM_PAT }}@github.com/${{ github.repository }}.git" main

      - name: Check if block.txt exists
        run: |
          set -e
          if [ ! -f block.txt ]; then
            echo "block.txt not found"
            exit 1
          fi

      - name: Check for meta.json
        run: |
          set -e
          if [ ! -f meta.json ]; then
            echo "meta.json not found"
            exit 1
          fi

      - name: Generate random string and rename block.txt
        id: hash_and_rename
        run: |
          set -e
          FILE_HASH=$(sha1sum block.txt | awk '{print $1}' | cut -c1-10)
          RANDOM_HASH=$(openssl rand -base64 24 | tr -dc 'a-z0-9' | head -c 6)
          echo "File hash: $FILE_HASH"
          echo "Random hash: $RANDOM_HASH"
          NEWFILE="block.${FILE_HASH}.${RANDOM_HASH}.txt"
          git mv block.txt "$NEWFILE"
          echo "newfile=$NEWFILE" >> $GITHUB_ENV

      - name: Remove previous blocklist file
        id: remove_old_block
        run: |
          set -e
          OLD=$(jq -r '.blocklist // empty' meta.json)
          if [ -n "$OLD" ] && [ -f "$OLD" ]; then
            echo "Removing old blocklist file: $OLD"
            git rm "$OLD"
          else
            echo "No old blocklist file to remove"
          fi

      - name: Update meta.json with new blocklist file
        id: update_meta
        run: |
          set -e
          NEWFILE="${{ env.newfile }}"
          jq --arg fn "$NEWFILE" '.blocklist = $fn' meta.json > meta.tmp && mv meta.tmp meta.json

      - name: Commit and push changes
        id: commit_and_push
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "${{ env.newfile }}" meta.json
          git commit -m "[ACTION] Obfuscate blocklist" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.CUSTOM_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
