name: Obfuscate allowlist to avoid use of direct raw url of allow.txt

on:
  push:
    branches:
      - main
    paths:
      - allow.txt

jobs:
  obfuscate-allowlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes with rebase
        id: pull_rebase_latest
        run: |
          set -e
          git pull --rebase "https://x-access-token:${{ secrets.CUSTOM_PAT }}@github.com/${{ github.repository }}.git" main

      - name: Check if allow.txt exists
        run: |
          set -e
          if [ ! -f allow.txt ]; then
            echo "allow.txt not found"
            exit 1
          fi

      - name: Check for meta.json
        run: |
          set -e
          if [ ! -f meta.json ]; then
            echo "meta.json not found"
            exit 1
          fi

      - name: Generate random string and rename allow.txt
        id: hash_and_rename
        run: |
          set -e
          HASH=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9' | head -c 16)
          echo "Generated hash: $HASH"
          NEWFILE="allow-$HASH.txt"
          git mv allow.txt "$NEWFILE"
          echo "newfile=$NEWFILE" >> $GITHUB_ENV

      - name: Remove previous allowlist file
        id: remove_old_allow
        run: |
          set -e
          OLD=$(jq -r '.allowlist // empty' meta.json)
          if [ -n "$OLD" ] && [ -f "$OLD" ]; then
            echo "Removing old allowlist file: $OLD"
            git rm "$OLD"
          else
            echo "No old allowlist file to remove"
          fi

      - name: Update meta.json with new allowlist file
        id: update_meta
        run: |
          set -e
          NEWFILE="${{ env.newfile }}"
          jq --arg fn "$NEWFILE" '.allowlist = $fn' meta.json > meta.tmp && mv meta.tmp meta.json

      - name: Commit and push changes
        id: commit_and_push
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "${{ env.newfile }}" meta.json
          git commit -m "[ACTION] Obfuscate allowlist" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.CUSTOM_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
