name: Obfuscate blocklist to avoid use of direct raw url of block.txt

on:
  push:
    branches:
      - main
    paths:
      - block.txt

jobs:
  obfuscate-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate hash and rename block.txt
        id: hash_and_rename
        run: |
          if [ -f block.txt ]; then
            HASH=$(sha256sum block.txt | cut -c1-16)
            echo "HASH: $HASH"
            NEWFILE="block-$HASH.txt"
            git mv block.txt "$NEWFILE"
            echo "newfile=$NEWFILE" >> $GITHUB_ENV
          else
            echo "block.txt not found."
          fi

      - name: Remove previous blocklist file
        id: remove_old_block
        run: |
          if [ -f meta.json ]; then
            OLD=$(jq -r '.blocklist // empty' meta.json)
            echo "OLD block file from meta.json: $OLD"
            if [ -n "$OLD" ] && [ -f "$OLD" ]; then
              git rm "$OLD"
            else
              echo "No old blocklist file to remove."
            fi
          else
            echo "meta.json not found."
          fi

      - name: Update meta.json with new block file
        id: update_meta
        run: |
          NEWFILE="${{ env.newfile }}"
          echo "Updating meta.json with: $NEWFILE"
          if [ -f meta.json ]; then
            jq --arg fn "$NEWFILE" '.blocklist = $fn' meta.json > meta.tmp && mv meta.tmp meta.json
          else
            echo "meta.json not found."
          fi

      - name: Commit and push changes
        id: commit_and_push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "${{ env.newfile }}" meta.json
          git commit -m "[ACTION] Obfuscate blocklist" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.CUSTOM_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
